- hosts: all
  tasks:
    - name: "install httpd software"
      package:
        name: "httpd"
        state: present

    - name: "install php"
      package:
        name: "php"
        state: present

    - name: "copy webpage to target node"
      copy:
        src: "index.html"
        dest: "/var/www/html/webpage.html"

    - name: "Start webServices"
      service:
        name: "httpd"
        state: started
        enabled: true
